
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND COLON COMMAND CONNECT DIRECTION DO GET ID IN IS ITEM ITEMS NOT OR PRINT RELEASE ROOM STRING WHENgame_spec : statement_liststatement_list : statementstatement_list : statement_list statementstatement : room_def\n                 | connect_def\n                 | item_def\n                 | command_defroom_def : ROOM ID STRINGconnect_def : CONNECT ID DIRECTION IDitem_def : ITEM ID STRING IN IDcommand_def : COMMAND ID ID COLON WHEN condition DO action_listcondition : ID IN ITEMS\n                 | ROOM IS STRINGaction_list : actionaction_list : action_list AND actionaction : PRINT STRING\n              | GET ID\n              | RELEASE ID'
    
_lr_action_items = {'ROOM':([0,2,3,4,5,6,7,12,17,21,24,25,33,34,40,41,42,43,],[8,8,-2,-4,-5,-6,-7,-3,-8,-9,-10,28,-11,-14,-16,-17,-18,-15,]),'CONNECT':([0,2,3,4,5,6,7,12,17,21,24,33,34,40,41,42,43,],[9,9,-2,-4,-5,-6,-7,-3,-8,-9,-10,-11,-14,-16,-17,-18,-15,]),'ITEM':([0,2,3,4,5,6,7,12,17,21,24,33,34,40,41,42,43,],[10,10,-2,-4,-5,-6,-7,-3,-8,-9,-10,-11,-14,-16,-17,-18,-15,]),'COMMAND':([0,2,3,4,5,6,7,12,17,21,24,33,34,40,41,42,43,],[11,11,-2,-4,-5,-6,-7,-3,-8,-9,-10,-11,-14,-16,-17,-18,-15,]),'$end':([1,2,3,4,5,6,7,12,17,21,24,33,34,40,41,42,43,],[0,-1,-2,-4,-5,-6,-7,-3,-8,-9,-10,-11,-14,-16,-17,-18,-15,]),'ID':([8,9,10,11,16,18,22,25,36,37,],[13,14,15,16,20,21,24,26,41,42,]),'STRING':([13,15,31,35,],[17,19,38,40,]),'DIRECTION':([14,],[18,]),'IN':([19,26,],[22,29,]),'COLON':([20,],[23,]),'WHEN':([23,],[25,]),'DO':([27,32,38,],[30,-12,-13,]),'IS':([28,],[31,]),'ITEMS':([29,],[32,]),'PRINT':([30,39,],[35,35,]),'GET':([30,39,],[36,36,]),'RELEASE':([30,39,],[37,37,]),'AND':([33,34,40,41,42,43,],[39,-14,-16,-17,-18,-15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'game_spec':([0,],[1,]),'statement_list':([0,],[2,]),'statement':([0,2,],[3,12,]),'room_def':([0,2,],[4,4,]),'connect_def':([0,2,],[5,5,]),'item_def':([0,2,],[6,6,]),'command_def':([0,2,],[7,7,]),'condition':([25,],[27,]),'action_list':([30,],[33,]),'action':([30,39,],[34,43,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> game_spec","S'",1,None,None,None),
  ('game_spec -> statement_list','game_spec',1,'p_game_spec','parser.py',15),
  ('statement_list -> statement','statement_list',1,'p_statement_list_single','parser.py',19),
  ('statement_list -> statement_list statement','statement_list',2,'p_statement_list_multiple','parser.py',23),
  ('statement -> room_def','statement',1,'p_statement','parser.py',27),
  ('statement -> connect_def','statement',1,'p_statement','parser.py',28),
  ('statement -> item_def','statement',1,'p_statement','parser.py',29),
  ('statement -> command_def','statement',1,'p_statement','parser.py',30),
  ('room_def -> ROOM ID STRING','room_def',3,'p_room_def','parser.py',34),
  ('connect_def -> CONNECT ID DIRECTION ID','connect_def',4,'p_connect_def','parser.py',45),
  ('item_def -> ITEM ID STRING IN ID','item_def',5,'p_item_def','parser.py',56),
  ('command_def -> COMMAND ID ID COLON WHEN condition DO action_list','command_def',8,'p_command_def','parser.py',75),
  ('condition -> ID IN ITEMS','condition',3,'p_condition','parser.py',93),
  ('condition -> ROOM IS STRING','condition',3,'p_condition','parser.py',94),
  ('action_list -> action','action_list',1,'p_action_list_single','parser.py',104),
  ('action_list -> action_list AND action','action_list',3,'p_action_list_multiple','parser.py',108),
  ('action -> PRINT STRING','action',2,'p_action','parser.py',113),
  ('action -> GET ID','action',2,'p_action','parser.py',114),
  ('action -> RELEASE ID','action',2,'p_action','parser.py',115),
]
